"""init

Revision ID: 410018418911
Revises: 
Create Date: 2026-07-22 12:50:15.802732

"""
from alembic import op
import sqlalchemy as sa


revision = '410018418911'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employers',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('work_email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('designation', sa.String(), nullable=True),
    sa.Column('created_via', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employers_work_email'), 'employers', ['work_email'], unique=True)
    op.create_table('students',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('obe_student_id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('enrollment_number', sa.String(), nullable=False),
    sa.Column('degree_program', sa.String(), nullable=True),
    sa.Column('batch', sa.String(), nullable=True),
    sa.Column('current_semester', sa.String(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_obe_student_id'), 'students', ['obe_student_id'], unique=True)
    op.create_table('engagements',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('student_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('employer_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('type', sa.Enum('internship', 'job', name='engagementtype'), nullable=False),
    sa.Column('status', sa.Enum('active', 'completed', 'archived', name='engagementstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['employer_id'], ['employers.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('magic_links',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('employer_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['employer_id'], ['employers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_magic_links_token'), 'magic_links', ['token'], unique=True)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('employer_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['employer_id'], ['employers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_token'), 'sessions', ['token'], unique=True)
    op.create_table('employer_surveys',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('engagement_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('survey_year', sa.String(), nullable=False),
    sa.Column('current_job_role', sa.String(), nullable=True),
    sa.Column('employment_department', sa.String(), nullable=True),
    sa.Column('employment_duration', sa.String(), nullable=True),
    sa.Column('rating_core_knowledge', sa.SmallInteger(), nullable=True),
    sa.Column('rating_knowledge_application', sa.SmallInteger(), nullable=True),
    sa.Column('rating_problem_solving', sa.SmallInteger(), nullable=True),
    sa.Column('rating_dev_contribution', sa.SmallInteger(), nullable=True),
    sa.Column('rating_tool_usage', sa.SmallInteger(), nullable=True),
    sa.Column('rating_teamwork', sa.SmallInteger(), nullable=True),
    sa.Column('rating_communication', sa.SmallInteger(), nullable=True),
    sa.Column('rating_professionalism', sa.SmallInteger(), nullable=True),
    sa.Column('rating_ethics', sa.SmallInteger(), nullable=True),
    sa.Column('rating_learning_attitude', sa.SmallInteger(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('engagement_id', 'survey_year', name='uq_survey_per_year')
    )
    op.create_table('internship_evaluations',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('engagement_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('rating_core_knowledge', sa.SmallInteger(), nullable=True),
    sa.Column('rating_problem_solving', sa.SmallInteger(), nullable=True),
    sa.Column('rating_dev_contribution', sa.SmallInteger(), nullable=True),
    sa.Column('rating_tool_usage', sa.SmallInteger(), nullable=True),
    sa.Column('rating_teamwork', sa.SmallInteger(), nullable=True),
    sa.Column('rating_communication', sa.SmallInteger(), nullable=True),
    sa.Column('rating_societal_awareness', sa.SmallInteger(), nullable=True),
    sa.Column('rating_ethics', sa.SmallInteger(), nullable=True),
    sa.Column('rating_learning_attitude', sa.SmallInteger(), nullable=True),
    sa.Column('attendance_bracket', sa.String(), nullable=True),
    sa.Column('task_completion', sa.String(), nullable=True),
    sa.Column('overall_rating', sa.String(), nullable=True),
    sa.Column('recommend', sa.Enum('yes', 'no', 'maybe', name='recommend'), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('engagement_id')
    )
    op.create_table('org_proformas',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('engagement_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_name', sa.String(), nullable=False),
    sa.Column('role_designation', sa.String(), nullable=True),
    sa.Column('department_served', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('supervisor_name', sa.String(), nullable=False),
    sa.Column('supervisor_designation', sa.String(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=False),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('submitted_by_student_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('validated_by_employer_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('validation_status', sa.Enum('pending', 'validated', 'edited', name='validationstatus'), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('engagement_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('org_proformas')
    op.drop_table('internship_evaluations')
    op.drop_table('employer_surveys')
    op.drop_index(op.f('ix_sessions_token'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_magic_links_token'), table_name='magic_links')
    op.drop_table('magic_links')
    op.drop_table('engagements')
    op.drop_index(op.f('ix_students_obe_student_id'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_employers_work_email'), table_name='employers')
    op.drop_table('employers')
    # ### end Alembic commands ###
